// Mock TMDB data for sandbox testing (no API key needed)
export const mockMovies = [
  { id: 1, title: "Project Hail Mary", poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg", backdrop_path: "/p1F51Lvj3sMVwEmhV2e4Jx7r5gF.jpg", overview: "Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there.", release_date: "2026-03-20", vote_average: 8.7, media_type: "movie", genre_ids: [878, 18] },
  { id: 2, title: "Moana 2", poster_path: "/yh64qw9mgXBvlaWDi7Q9tpUBAvM.jpg", backdrop_path: "/tElnmtQ6yz1PjN1kePNp8JMR3U.jpg", overview: "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania.", release_date: "2024-11-27", vote_average: 7.2, media_type: "movie", genre_ids: [16, 12, 10751] },
  { id: 3, title: "Dune: Part Two", poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg", backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5hjhFP.jpg", overview: "Paul Atreides unites with Chani and the Fremen while seeking revenge against those who destroyed his family.", release_date: "2024-03-01", vote_average: 8.5, media_type: "movie", genre_ids: [878, 12, 28] },
  { id: 4, title: "The Batman", poster_path: "/74xTEUT7IYf1XoVX7P6S0A2z5z5.jpg", backdrop_path: "/5P8SmMzSNYikXpxil6BYZJd9z2.jpg", overview: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption.", release_date: "2022-03-04", vote_average: 7.7, media_type: "movie", genre_ids: [80, 9648, 53] },
  { id: 5, title: "Spider-Man: Across the Spider-Verse", poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg", backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg", overview: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.", release_date: "2023-06-02", vote_average: 8.3, media_type: "movie", genre_ids: [16, 28, 12] },
  { id: 6, title: "Oppenheimer", poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", backdrop_path: "/nb3xI8XI3w4pMVnZ9y3S7wQZ0W.jpg", overview: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", release_date: "2023-07-21", vote_average: 8.1, media_type: "movie", genre_ids: [18, 36] },
  { id: 7, title: "Deadpool & Wolverine", poster_path: "/jbwYaoM1nT1X5r2W4q2p3x8z9y.jpg", backdrop_path: "/yDHYTrZ0y6hB8P8x8x8x8x8x8x.jpg", overview: "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him.", release_date: "2024-07-26", vote_average: 7.6, media_type: "movie", genre_ids: [28, 35, 878] },
  { id: 8, title: "Inside Out 2", poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2.jpg", backdrop_path: "/x8x8x8x8x8x8x8x8x8x8x8x8x8x.jpg", overview: "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions.", release_date: "2024-06-14", vote_average: 7.6, media_type: "movie", genre_ids: [16, 35, 12, 10751] },
  { id: 9, title: "Gladiator II", poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z.jpg", backdrop_path: "/x8x8x8x8x8x8x8x8x8x8x8x8x8x.jpg", overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum.", release_date: "2024-11-22", vote_average: 6.7, media_type: "movie", genre_ids: [28, 12, 18] },
  { id: 10, title: "Wicked", poster_path: "/x8x8x8x8x8x8x8x8x8x8x8x8x8x.jpg", backdrop_path: "/x8x8x8x8x8x8x8x8x8x8x8x8x8x.jpg", overview: "Elphaba, a misunderstood young woman because of her green skin, and Galinda, a popular girl, become friends at Shiz University.", release_date: "2024-11-22", vote_average: 7.5, media_type: "movie", genre_ids: [18, 10749, 14] },
]

export const mockTVShows = [
  { id: 101, name: "Squid Game", poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg", backdrop_path: "/x8x8x8x8x8x8x8x8x8x8x8x8x8x.jpg", overview: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games.", first_air_date: "2021-09-17", vote_average: 7.8, media_type: "tv", genre_ids: [10759, 9648, 18] },
  { id: 102, name: "The Last of Us", poster_path: "/uKvVjHNqB5VmOrhGFrxsiplPkw9.jpg", backdrop_path: "/x8x8x8x8x8x8x8x8x8x8x8x8x8x.jpg", overview: "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie out of an oppressive quarantine zone.", first_air_date: "2023-01-15", vote_average: 8.4, media_type: "tv", genre_ids: [18, 10759, 9648] },
  { id: 103, name: "House of the Dragon", poster_path: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg", backdrop_path: "/x8x8x8x8x8x8x8x8x8x8x8x8x8x.jpg", overview: "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke.", first_air_date: "2022-08-21", vote_average: 8.1, media_type: "tv", genre_ids: [10765, 18, 10759] },
  { id: 104, name: "The Bear", poster_path: "/x8x8x8x8x8x8x8x8x8x8x8x8x8x.jpg", backdrop_path: "/x8x8x8x8x8x8x8x8x8x8x8x8x8x.jpg", overview: "A young chef from the fine dining world comes home to Chicago to run his family sandwich shop.", first_air_date: "2022-06-23", vote_average: 8.3, media_type: "tv", genre_ids: [18, 35] },
  { id: 105, name: "Severance", poster_path: "/x8x8x8x8x8x8x8x8x8x8x8x8x8x.jpg", backdrop_path: "/x8x8x8x8x8x8x8x8x8x8x8x8x8x.jpg", overview: "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.", first_air_date: "2022-02-18", vote_average: 8.5, media_type: "tv", genre_ids: [18, 9648, 878] },
]

export const mockHeroMedia = mockMovies[0]
